version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: whalewkss_pg
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: whalewkss
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - app-network

  app:
    image: go-fiber:test #เปลี่ยนเป็น images ล่าสุดของตัวเองนา
    container_name: go-fiber-container
    volumes:
      - ./pdf-files:/app/pdf-files
    ports:
      - "8080:8080"
    environment:
      DB_URI: postgresql://admin:admin@postgres:5432/whalewkss
      SECRET_KEYS: secretkeys
      PDF_DIR: /app/pdf-files/
    networks:
      - app-network

networks:
  app-network:
    external: true
